namespace DependencyInjection.SourceGenerator;

/// <summary> 内部调用类 </summary>
internal partial class SourceGenerator
{
    /// <summary>
    /// Services 服务注入
    /// </summary>
    internal const string GENERATE_SOURCE = @"// <auto-generated>
//     由 DependencyInjection.SourceGenerator 自动生成.
//     Assembly：{0}.dll
// </auto-generated>

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

/// <summary>
/// ServiceCollectionExtensions_G.cs 服务自动注入到IOC扩展类
/// </summary>
public static class {1}
{
    /// <summary>
    /// {0}.dll 程序集中的所有标记类型添加到指定程序集的给定服务集合中
    /// </summary>
    /// <param name=""services""> <see cref=""IServiceCollection"" /> </param> 
    /// <returns> <see cref=""IServiceCollection"" /> </returns>
    public static Microsoft.Extensions.DependencyInjection.IServiceCollection Add{2}(this Microsoft.Extensions.DependencyInjection.IServiceCollection services
        , Microsoft.Extensions.Configuration.IConfiguration configuration)
    {
{3}
        return services;
    }
}";
}